//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int CitaId { get; set; }
        public string Especialidad { get; set; }
        public string Dosis { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal CostoCita { get; set; }
        public decimal CostoTotal { get; set; }
        public int CodigoMascota { get; set; }
        public int CodigoVeterinario { get; set; }
        public int CodigoMedicamento { get; set; }
        public bool Activa { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualizacion { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
